const makeQuestion = (text, options, correctIndex, topic, difficulty) => ({
  text,
  options,
  correctIndex,
  topic,
  difficulty,
  createdAt: '2026-08-22T00:00:00.000Z',
  isDefault: true,
});

export const DEFAULT_QUESTIONS = [
  makeQuestion('Một tuần có bao nhiêu ngày?', ['7 ngày', '5 ngày', '6 ngày', '8 ngày'], 0, 'Thường thức', 'easy'),
  makeQuestion('Khi đèn giao thông màu đỏ, người đi đường phải làm gì?', ['Dừng lại', 'Đi thật nhanh', 'Rẽ bất kỳ hướng nào', 'Bấm còi liên tục'], 0, 'An toàn giao thông', 'easy'),
  makeQuestion('Bộ phận nào giúp chúng ta nhìn thấy mọi vật?', ['Mắt', 'Tai', 'Mũi', 'Tay'], 0, 'Thường thức', 'easy'),
  makeQuestion('Buổi sáng, Mặt Trời thường mọc ở hướng nào?', ['Đông', 'Tây', 'Nam', 'Bắc'], 0, 'Thường thức', 'easy'),
  makeQuestion('Con vật nào dưới đây sống dưới nước?', ['Cá chép', 'Con mèo', 'Con gà', 'Con thỏ'], 0, 'Tự nhiên', 'easy'),
  makeQuestion('Kết quả của 8 + 7 là bao nhiêu?', ['15', '14', '16', '17'], 0, 'Toán học', 'easy'),
  makeQuestion('Kết quả của 20 - 9 là bao nhiêu?', ['11', '10', '12', '9'], 0, 'Toán học', 'easy'),
  makeQuestion('Số nào lớn nhất trong các số 18, 81, 28 và 78?', ['81', '18', '28', '78'], 0, 'Toán học', 'easy'),
  makeQuestion('Hình có ba cạnh được gọi là hình gì?', ['Hình tam giác', 'Hình vuông', 'Hình tròn', 'Hình chữ nhật'], 0, 'Toán học', 'easy'),
  makeQuestion('Một mét bằng bao nhiêu xăng-ti-mét?', ['100 cm', '10 cm', '1.000 cm', '50 cm'], 0, 'Toán học', 'easy'),
  makeQuestion('Từ nào dưới đây chỉ hoạt động?', ['Chạy', 'Cây bút', 'Màu đỏ', 'Hiền lành'], 0, 'Tiếng Việt', 'easy'),
  makeQuestion('Từ nào viết đúng chính tả?', ['nghỉ ngơi', 'ngỉ ngơi', 'nghĩ nghơi', 'nghỉ nghơi'], 0, 'Tiếng Việt', 'easy'),
  makeQuestion('Trong câu “Lan đang đọc sách”, ai là người thực hiện hoạt động?', ['Lan', 'đang', 'đọc', 'sách'], 0, 'Tiếng Việt', 'easy'),
  makeQuestion('Từ nào đồng nghĩa với “siêng năng”?', ['Chăm chỉ', 'Lười biếng', 'Chậm chạp', 'Ồn ào'], 0, 'Tiếng Việt', 'easy'),
  makeQuestion('Câu nào dưới đây là câu hỏi?', ['Bạn học lớp mấy?', 'Em học lớp năm.', 'Hãy mở sách ra!', 'Ôi, đẹp quá!'], 0, 'Tiếng Việt', 'easy'),
  makeQuestion('Từ tiếng Anh “book” có nghĩa là gì?', ['Quyển sách', 'Cây bút', 'Cái bàn', 'Trường học'], 0, 'Tiếng Anh', 'easy'),
  makeQuestion('Từ trái nghĩa với “big” là từ nào?', ['small', 'tall', 'long', 'fast'], 0, 'Tiếng Anh', 'easy'),
  makeQuestion('Chọn từ đúng để hoàn thành câu: “I ___ a student.”', ['am', 'is', 'are', 'be'], 0, 'Tiếng Anh', 'easy'),
  makeQuestion('Màu “blue” trong tiếng Anh là màu gì?', ['Màu xanh dương', 'Màu đỏ', 'Màu vàng', 'Màu đen'], 0, 'Tiếng Anh', 'easy'),
  makeQuestion('Câu “Good morning” thường dùng để chào vào lúc nào?', ['Buổi sáng', 'Buổi trưa', 'Buổi tối', 'Trước khi ngủ'], 0, 'Tiếng Anh', 'easy'),
  makeQuestion('Kết quả của 36 × 4 là bao nhiêu?', ['144', '124', '136', '164'], 0, 'Toán học', 'medium'),
  makeQuestion('Một hình vuông có cạnh 7 cm. Chu vi của hình vuông là bao nhiêu?', ['28 cm', '49 cm', '14 cm', '21 cm'], 0, 'Toán học', 'medium'),
  makeQuestion('Phân số nào bằng một nửa?', ['2/4', '2/3', '3/4', '1/3'], 0, 'Toán học', 'medium'),
  makeQuestion('Một lớp có 35 học sinh chia đều thành 5 nhóm. Mỗi nhóm có bao nhiêu học sinh?', ['7', '5', '6', '8'], 0, 'Toán học', 'medium'),
  makeQuestion('Số tiếp theo trong dãy 5, 10, 15, 20 là số nào?', ['25', '22', '24', '30'], 0, 'Toán học', 'medium'),
  makeQuestion('Bộ phận nào của cây hút nước và muối khoáng từ đất?', ['Rễ', 'Lá', 'Hoa', 'Quả'], 0, 'Khoa học', 'medium'),
  makeQuestion('Con người cần khí nào để hô hấp?', ['Ô-xi', 'Cacbonic', 'Hiđrô', 'Nitơ'], 0, 'Khoa học', 'medium'),
  makeQuestion('Nước chuyển từ thể lỏng sang thể khí được gọi là gì?', ['Bay hơi', 'Đông đặc', 'Ngưng tụ', 'Nóng chảy'], 0, 'Khoa học', 'medium'),
  makeQuestion('Nguồn năng lượng nào dưới đây là năng lượng tái tạo?', ['Ánh sáng Mặt Trời', 'Than đá', 'Dầu mỏ', 'Khí tự nhiên'], 0, 'Khoa học', 'medium'),
  makeQuestion('Hành tinh nào gần Mặt Trời nhất?', ['Sao Thủy', 'Trái Đất', 'Sao Hỏa', 'Sao Mộc'], 0, 'Khoa học', 'medium'),
  makeQuestion('Thủ đô của Việt Nam là thành phố nào?', ['Hà Nội', 'Huế', 'Đà Nẵng', 'Hải Phòng'], 0, 'Địa lý', 'medium'),
  makeQuestion('Việt Nam nằm ở khu vực nào của châu Á?', ['Đông Nam Á', 'Đông Á', 'Nam Á', 'Trung Á'], 0, 'Địa lý', 'medium'),
  makeQuestion('Đồng bằng lớn nhất Việt Nam là đồng bằng nào?', ['Đồng bằng sông Cửu Long', 'Đồng bằng sông Hồng', 'Đồng bằng duyên hải miền Trung', 'Cao nguyên Mộc Châu'], 0, 'Địa lý', 'medium'),
  makeQuestion('Dãy núi dài nhất Việt Nam là dãy núi nào?', ['Trường Sơn', 'Hoàng Liên Sơn', 'Tam Đảo', 'Bạch Mã'], 0, 'Địa lý', 'medium'),
  makeQuestion('Châu lục nào có diện tích lớn nhất thế giới?', ['Châu Á', 'Châu Âu', 'Châu Phi', 'Châu Đại Dương'], 0, 'Địa lý', 'medium'),
  makeQuestion('Ai là người đọc Tuyên ngôn Độc lập ngày 2 tháng 9 năm 1945?', ['Chủ tịch Hồ Chí Minh', 'Đại tướng Võ Nguyên Giáp', 'Phan Bội Châu', 'Trần Hưng Đạo'], 0, 'Lịch sử', 'medium'),
  makeQuestion('Chiến thắng Điện Biên Phủ diễn ra vào năm nào?', ['1954', '1945', '1975', '1968'], 0, 'Lịch sử', 'medium'),
  makeQuestion('Vị vua nào dời đô từ Hoa Lư ra Thăng Long?', ['Lý Công Uẩn', 'Đinh Tiên Hoàng', 'Lê Lợi', 'Quang Trung'], 0, 'Lịch sử', 'medium'),
  makeQuestion('Nhà Trần ba lần chiến thắng quân xâm lược nào?', ['Nguyên – Mông', 'Minh', 'Thanh', 'Tống'], 0, 'Lịch sử', 'medium'),
  makeQuestion('Ngày Quốc khánh Việt Nam là ngày nào?', ['2 tháng 9', '30 tháng 4', '1 tháng 5', '20 tháng 11'], 0, 'Lịch sử', 'medium'),
  makeQuestion('Một cửa hàng có 240 kg gạo, đã bán 3/8 số gạo. Cửa hàng còn lại bao nhiêu ki-lô-gam gạo?', ['150 kg', '90 kg', '120 kg', '180 kg'], 0, 'Toán học', 'hard'),
  makeQuestion('Trung bình cộng của ba số 24, 36 và 48 là bao nhiêu?', ['36', '32', '38', '40'], 0, 'Toán học', 'hard'),
  makeQuestion('Một hình chữ nhật dài 12 cm, rộng 8 cm. Diện tích hình chữ nhật là bao nhiêu?', ['96 cm²', '40 cm²', '20 cm²', '192 cm²'], 0, 'Toán học', 'hard'),
  makeQuestion('Số thập phân 0,75 được viết dưới dạng phân số tối giản là phân số nào?', ['3/4', '7/5', '1/4', '75/10'], 0, 'Toán học', 'hard'),
  makeQuestion('Một ô tô đi 180 km trong 3 giờ với vận tốc không đổi. Vận tốc của ô tô là bao nhiêu?', ['60 km/giờ', '90 km/giờ', '54 km/giờ', '45 km/giờ'], 0, 'Toán học', 'hard'),
  makeQuestion('Trong chuỗi thức ăn “lúa → châu chấu → ếch → rắn”, sinh vật sản xuất là sinh vật nào?', ['Lúa', 'Châu chấu', 'Ếch', 'Rắn'], 0, 'Khoa học', 'hard'),
  makeQuestion('Hiện tượng hơi nước gặp lạnh biến thành giọt nước gọi là gì?', ['Ngưng tụ', 'Bay hơi', 'Nóng chảy', 'Đông đặc'], 0, 'Khoa học', 'hard'),
  makeQuestion('Vì sao cần trồng nhiều cây xanh ở khu dân cư?', ['Cây hấp thụ khí cacbonic và tạo ô-xi', 'Cây làm không khí nóng hơn', 'Cây tạo ra khói', 'Cây làm giảm lượng nước sạch'], 0, 'Khoa học', 'hard'),
  makeQuestion('Câu nào dưới đây có trạng ngữ chỉ thời gian?', ['Sáng nay, chúng em trồng cây.', 'Chúng em trồng cây trong sân.', 'Chúng em trồng cây bằng xẻng.', 'Chúng em vui vẻ trồng cây.'], 0, 'Tiếng Việt', 'hard'),
  makeQuestion('Trong câu “Những chú chim nhỏ đang ríu rít trên cành”, chủ ngữ là bộ phận nào?', ['Những chú chim nhỏ', 'đang ríu rít', 'trên cành', 'ríu rít trên cành'], 0, 'Tiếng Việt', 'hard'),
];

